type Query {
    """Query a Line using ID"""
    getLine(id: ID!): LineById
}

type LineById implements Line & MetaInfo{
    id: ID!
    shabadid: ID!
    gurmukhi: LineDefaults!
    larivaar: LineDefaults!
	translation: Translations!
	transliteration: Transliterations!
    source: LineSource!
    writer: Writer!
    raag: Raag!
	lineNum: Int!
	firstletters: LineDefaults!
}

type LineSource implements defaults & Source {
    id: ID!
    akhar: String!
    unicode: String!
    english: String!
    pageName: Name!
}